name: Deploy

on:
  workflow_run:
    workflows: [".NET"]
    branches: [master]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Push changes to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
      - name: Trigger rebuild
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} ~/Thorn/deploy.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Not deploying
        run: echo "Not deploying"